<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Adidas',
            'model'=> 'UltraBoost',
            'nickname'=> 'Cool Grey',
            'color'=> 'Grey',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '149.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Adidas',
            'model'=> 'Powerlift',
            'nickname'=> 'Cloud White',
            'color'=> 'White',
            'gender'=> 'Women',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'DS3240-400',
            'price'=> '99.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'On Sale',
            'brand'=> 'Adidas',
            'model'=> 'Originals',
            'nickname'=> 'Frozen Gold',
            'color'=> 'Gold',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3340-800',
            'price'=> '249.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Nike',
            'model'=> 'Air Force 1',
            'nickname'=> 'University Red',
            'color'=> 'Red',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AD3240-800',
            'price'=> '129.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Nike',
            'model'=> 'Air Max',
            'nickname'=> 'Electric Green',
            'color'=> 'Green',
            'gender'=> 'Women',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'DS3240-800',
            'price'=> '59.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'On Sale',
            'brand'=> 'Nike',
            'model'=> 'Continental',
            'nickname'=> 'Salt',
            'color'=> 'Blue',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '69.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Air Jordan',
            'model'=> '10',
            'nickname'=> 'Gym Red',
            'color'=> 'Red',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '79.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'On Sale',
            'brand'=> 'Yeezy',
            'model'=> 'Boost 350',
            'nickname'=> 'New Grey',
            'color'=> 'Grey',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '219.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Vans',
            'model'=> 'Era Pro',
            'nickname'=> 'Black Cement',
            'color'=> 'Black',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '69.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Converse',
            'model'=> 'Chuck Taylor',
            'nickname'=> 'Vachetta',
            'color'=> 'Blue',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '189.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Reebok',
            'model'=> 'Royal Glide',
            'nickname'=> 'Gold Hour',
            'color'=> 'Gold',
            'gender'=> 'Women',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '139.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Puma',
            'model'=> 'Axis Trail',
            'nickname'=> 'Green Glimmer',
            'color'=> 'Green',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '229.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'On Sale',
            'brand'=> 'Vans',
            'model'=> 'Authentic Pro',
            'nickname'=> 'Patchwork',
            'color'=> 'Grey',
            'gender'=> 'Women',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '179.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Converse',
            'model'=> 'All-Star',
            'nickname'=> 'Play',
            'color'=> 'Red',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '279.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'On Sale',
            'brand'=> 'Reebok',
            'model'=> 'Slice USA',
            'nickname'=> 'Chalk',
            'color'=> 'White',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '49.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Air Jordan',
            'model'=> '13',
            'nickname'=> 'Off White',
            'color'=> 'White',
            'gender'=> 'Women',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '299.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Yeezy',
            'model'=> 'Chuck Taylor',
            'nickname'=> 'Ice Cold',
            'color'=> 'White',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '349.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('products')->insert([
            'collection'=> 'New Releases',
            'brand'=> 'Adidas',
            'model'=> 'UltraBoost',
            'nickname'=> 'Very Blue',
            'color'=> 'Blue',
            'gender'=> 'Men',
            'details'=> 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis mauris id nisl tincidunt, eu hendrerit sem efficitur. Cras eleifend diam leo. Nullam tincidunt nulla et lacus euismod congue. Aenean cursus tristique blandit. Integer et posuere ipsum, non maximus odio. Aenean a sapien nec tortor accumsan sollicitudin sed at augue.',
            'sku'=> 'AR3240-800',
            'price'=> '329.99',
            'created_at'=> Carbon::now(),
            'updated_at'=> Carbon::now(),
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);

        DB::table('sizes')->insert([
            '30' => '10',
            '31' => '10',
            '32' => '10',
            '33' => '10',
            '34' => '10',
            '35' => '10',
            '36' => '10',
            '37' => '10',
            '38' => '10',
            '39' => '10',
            '40' => '10',
            '41' => '10',
            '42' => '10',
            '43' => '10',
            '44' => '10',
            '45' => '10',
            '46' => '10',
            '47' => '10',
            '48' => '10',
            '49' => '10',
            '50' => '10',
        ]);
    }
}
